services:
  mongodb:
    image: mongo:7.0
    container_name: hn-challenge-mongodb
    ports:
      - '27017:27017'
    env_file:
      - ../apps/backend/.env
    environment:
      - DB_HOST=mongodb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    restart: unless-stopped

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: backend
    container_name: hn-challenge-backend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - ../apps/backend/.env
    restart: unless-stopped
    depends_on:
      - mongodb

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: frontend
    container_name: hn-challenge-frontend
    ports:
      - '3030:3030'
    environment:
      - PORT=3030
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  mongodb_data:
