version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: hn-challenge-backend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: ['pnpm', '--filter', '@hn-challenge/backend', 'start']
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: hn-challenge-frontend
    ports:
      - '3030:3030'
    environment:
      - PORT=3030
      - NODE_ENV=production
    command: ['pnpm', '--filter', '@hn-challenge/frontend', 'start']
    restart: unless-stopped
    depends_on:
      - backend
